Traceback (most recent call last):
  File "/fs01/home/opent03/detectron/run_mmd.py", line 117, in <module>
    main()
  File "/fs01/home/opent03/detectron/run_mmd.py", line 67, in main
    distance = DK_MMD(**mmd_config)
  File "/fs01/home/opent03/detectron/baselines/dkmmd.py", line 166, in __init__
    self.feature_map = self.feature_map.to(self.device)
  File "/h/opent03/.conda/envs/dis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/h/opent03/.conda/envs/dis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/h/opent03/.conda/envs/dis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/h/opent03/.conda/envs/dis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/h/opent03/.conda/envs/dis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

